/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:dd8901be44074168b05becf940320ef5:2989c4f83fc51eb2b4a0be79d84d45a2:392bb42978da344af36d8fe9bbfcaedc$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class PLSsprites
	{
		public const string Client_back = "Client_back";
		public const string Client_front = "Client_front";
		public const string Client_left = "Client_left";
		public const string Client_right = "Client_right";
		public const string Cr_back = "Cr_back";
		public const string Cr_front = "Cr_front";
		public const string Cr_left = "Cr_left";
		public const string Cr_right = "Cr_right";
		public const string Mh = "Mh";
		public const string Mh_back = "Mh_back";
		public const string Mh_front = "Mh_front";
		public const string Mh_left = "Mh_left";
		public const string Mh_right = "Mh_right";
		public const string Restaurant = "Restaurant";
		public const string Serveur_back = "Serveur_back";
		public const string Serveur_front = "Serveur_front";
		public const string Serveur_left = "Serveur_left";
		public const string Serveur_right = "Serveur_right";
	}
}