/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:5ba1c7618205e6824de2625b58fa7c50:82e08b458f5c115e06863cbed4e807f0:392bb42978da344af36d8fe9bbfcaedc$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class PLSsprites
    {
		public const string Mh = "mh";
		public const string Restaurant = "Restaurant";
	}
}